# 当分支 main 有 push 事件并且此次 push 包含了 components 目录下的文件时，执行以下任务
# cd components 目录下
# 发布 stdf 到 npm

name: Auto publish npm

on:
    push:
        branches:
            - main
        paths:
            - 'components/**'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x

            - name: Publish
              run: |
                  cd components
                  npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
                  npm publish
              env:
                  CI: true
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
