# 当分支 main 有 push 事件并且此次 push 包含了 components/package.json 文件时，执行以下任务

name: AUTO PUBLISH NPM

on:
    push:
        branches:
            - main
        paths:
            - 'components/package.json'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x

            # 将 REDME_en.md 复制到 components 目录下，并重命名为 README.md
            - name: Copy README
              run: |
                  cp README_en.md components/README.md

            # cd components 目录下
            # 发布 stdf 到 npm
            - name: Publish
              run: |
                  cd components
                  npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
                  npm publish
              env:
                  CI: true
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
