# 当分支 main 有 push 事件并且此次 push 包含了 packages/create-stdf/package.json 文件时，执行以下任务

name: PUBLISH CREATE

on:
    push:
        branches:
            - main
        paths:
            - 'packages/create-stdf/package.json'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x

            # 读取 packages/stdf/package.json 中的 version 字段，作为 stdf 的最新版本
            - name: Get version
              id: version
              run: |
                  echo version=$(cat packages/stdf/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]') >> $GITHUB_OUTPUT

              # 将 packages/create-stdf/templates/vite-tailwind/package.json 内的第 10 行增加内容为 stdf，版本号为 ${{ steps.version.outputs.version }}
            - name: Init create-stdf
              run: |
                  sed -i '10a\        "stdf": "^${{ steps.version.outputs.version }}",' packages/create-stdf/templates/vite-tailwind/package.json

            # cd packages/create-stdf 目录下
            # 安装依赖 npm install
            # 打包 npm run build
            # 发布 create-stdf 到 npm
            - name: Publish
              run: |
                  cd packages/create-stdf
                  npm install
                  npm run build 
                  npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
                  npm publish
              env:
                  CI: true
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_CREATE }}
